[package]
name = "makeup_syntect"
version = "0.1.4"
authors = []
edition = "2021"

[lib]
name = "makeup_syntect"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.37.2"
syntect = "5.2.0"
two-face = { version = "0.5.1", features = ["syntect-default-onig"] }
